/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package client

import platform.AssociativeArrayOf
import kotlin.test.Test
import kotlin.test.assertEquals

class TlcpEncodeTest {
    @Test
    fun `no encode`() {
        assertEquals("Hello!", TlcpEncodeString("Hello!"))
    }

    @Test
    fun `encode required`() {
        assertEquals("1%2B2%3D3", TlcpEncodeString("1+2=3"))
    }

    @Test
    fun `encode create session`() {
        val encoded = TlcpEncodeRequest(
                AssociativeArrayOf(
                        "LS_polling" to "true",
                        "LS_polling_millis" to "0",
                        "LS_cid" to "mgQkwtwdysogQz2BJ4Ji kOj2Bg",
                        "LS_adapter_set" to "WELCOME_HOME"
                )
        )
        // trailing "&" is optional
        assertEquals("LS_polling=true&LS_polling_millis=0&LS_cid=mgQkwtwdysogQz2BJ4Ji%20kOj2Bg&LS_adapter_set=WELCOME_HOME&", encoded)
    }
}
